# Generated by Django 3.0 on 2023-03-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CryptoIBook_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AddFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50, null=True)),
                ('about_product', models.CharField(max_length=50, null=True)),
                ('about_service', models.CharField(max_length=50, null=True)),
                ('comments', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AddPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50, null=True)),
                ('user_id', models.CharField(max_length=50, null=True)),
                ('payment_date', models.CharField(max_length=50, null=True)),
                ('paid_amount', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AddProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=50, null=True)),
                ('product_name', models.CharField(max_length=50, null=True)),
                ('uom', models.CharField(max_length=30, null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('price', models.IntegerField(null=True)),
                ('image', models.CharField(max_length=1000, null=True)),
                ('total_stock', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AddStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=50, null=True)),
                ('stock', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50, null=True)),
                ('product_name', models.CharField(max_length=50, null=True)),
                ('quantity', models.CharField(max_length=50, null=True)),
                ('unit_price', models.CharField(max_length=50, null=True)),
                ('total', models.CharField(max_length=50, null=True)),
                ('order_status', models.CharField(max_length=50, null=True)),
                ('payment_status', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OtpCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='userlogin',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='pincode',
            field=models.CharField(max_length=60),
        ),
    ]
