# Generated by Django 3.0 on 2023-03-14 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CryptoIBook_app', '0002_auto_20230309_2338'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddProduct',
            new_name='BlockChain',
        ),
    ]
